module.exports = {
  PLAY: {
    STROKE_WIDTH: '15px',
    STROKE_COLOR: 'black',
    TIME_LENGHT_CHARACTER: 250,
    WRITE_SCALE: 4,
    WRITE_STAGGERING_DELAY: 150, //ms
    DISSOLVE_STAGGERING_DELAY: 10, //ms
    ERASE_STAGGERING_DELAY: 100, //ms
    ERASE_SCALE: 4,
    WAVEIN_DURATION: 750, //ms
    WAVEIN_TRANSLATEY: '1.1em',
    WAVEIN_STAGGERING_DELAY: 50,
    // WAVEIN_DURATION_DIV: 1000,
    // WAVEIN_DELAY_DIV: 1000,
    WAVEOUT_DURATION: 2000,
    WAVEOUT_TRANSLATEY: '1em',
    WAVEOUT_STAGGERING_DELAY: 100,
    // WAVEOUT_DELAY_DIV: 1000,
    SPINOUT_DURATION: 2500,
    SPINOUT_STAGGERING_DELAY: 150
    // SPINOUT_DURATION_DIV: 1000,
    // SPINOUT_DELAY_DIV: 1000
  }
};